name: trm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  hooks_riverpod: ^2.0.2
  dio: ^4.0.6
  infinite_scroll_pagination: ^3.2.0
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.5
  connectivity_plus: ^3.0.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png